# Generated by Django 3.1.2 on 2021-08-31 08:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('CPD_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SlotBook',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(max_length=15)),
                ('district', models.CharField(max_length=15)),
                ('vaccine', models.CharField(max_length=15)),
                ('slot', models.DateField()),
                ('aadhaar', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='CPD_app.users')),
            ],
        ),
    ]
